Repository NiceTSY/nice-cypher-add-ons, pull requests merged in 2022-05, with the labels that each got.

#2 Fixing trading behavior
  scripts/add-ons.js
  scripts/module_trade.js
Labels: future

#16 Fix creation tool always deleting items & inline the settings panel
  scripts/add-ons.js
  scripts/module_creation.js
  scripts/settings.js
Labels: enhancement

#19 Add the MCG Fan Use Policy - Abbreviated Statement to the settings
  README.md
  img/Numenera-Kallis-by-Mirco-Paganessi.webp
  scripts/settings.js
  templates/add_ons_config.html
  templates/add_ons_mcg_fup.html
Labels: documentation
